name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Install dependencies
        run: |
          npm install
          cd client && npm install
      
      - name: Build with React Scripts
        run: |
          cd client
          npm run build
        env:
          REACT_APP_SUPABASE_URL: https://wrzwkrvtamhtxdgqlxve.supabase.co
          REACT_APP_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyendrcnZ0YW1odHhkZ3FseHZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTAyMjYsImV4cCI6MjA3MjMyNjIyNn0.K5huAAIxR2KAuwiILnySm5N0WH1dXS2R9QzntZ2HnCM
          CI: false
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './client/build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
